version: "2"

services:
  #############################
  # ELASTICSEARCH MASTER NODE #
  #############################
  elasticsearch:
    image: blacktop/elasticsearch:x-pack
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - network.host=0
      - ELASTIC_PASSWORD=pleasechangeme
      - xpack.security.transport.filter.enabled=false
      - xpack.security.audit.enabled=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    volumes:
      - /diskZ/esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic
  ###############
  # KIBANA NODE #
  ###############
  kibana:
    image: blacktop/kibana:x-pack
    environment:
      - elasticsearch.url=http://elasticsearch:9200
      - elasticsearch.username=elastic
      - elasticsearch.password=pleasechangeme
      - server.host=0.0.0.0
      # - xpack.monitoring.ui.container.elasticsearch.enabled=true
    ports:
      - "80:5601"
    links:
     - elasticsearch
    networks:
      - elastic
#############################
# ELASTICSEARCH DATA VOLUME #
#############################
# volumes:
#   data:
################################
# ELASTICSEARCH BRIDGE NETWORK #
################################
networks:
  elastic:
    driver: bridge

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
